"""add task model

Revision ID: 0093d750ba47
Revises: da83282d5777
Create Date: 2026-07-30 13:19:14.426662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0093d750ba47'
down_revision: Union[str, Sequence[str], None] = 'da83282d5777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('role', sa.Enum('MANAGER', 'DEVELOPER', name='teamrole', native_enum=False, length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'role')
    # ### end Alembic commands ###
