"""add dashboard query indexes

Revision ID: 746c3ee3d1a3
Revises: 9a7d78731892
Create Date: 2026-09-16 19:47:22.214172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746c3ee3d1a3'
down_revision: Union[str, Sequence[str], None] = '9a7d78731892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_assignee_status', 'tasks', ['assignee_id', 'status'], unique=False)
    op.create_index('ix_tasks_due_date_status', 'tasks', ['due_date', 'status'], unique=False)
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index('ix_tasks_due_date_status', table_name='tasks')
    op.drop_index('ix_tasks_assignee_status', table_name='tasks')
    # ### end Alembic commands ###
